
ENABLE_LINTERS:
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWNLINT
  - MAKEFILE_CHECKMAKE
  - BASH_SHELLCHECK

DISABLE_ERRORS_LINTERS:
  - MAKEFILE_CHECKMAKE


REPOSITORY_KICS_ARGUMENTS: "--fail-on high"