repos:
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.42.0
    hooks:
      - id: semgrep
        name: Semgrep Python
        types: [python]
        args: ["--config", "p/python", "--error"]
      - id: semgrep
        name: Semgrep Bandit
        types: [python]
        args: ["--config", "p/bandit", "--error"]